# This is a basic workflow to help you get started with Actions

name: build and deploy to AWS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo content
        uses: actions/checkout@v3
        with:
          submodules: true
        
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python script dependancies
        run: pip3 install pillow requests beautifulsoup4
        
      - name: Getting ufg-member-pics
        run: python3 ../../script/get-ufg-pic.py
        working-directory: ./public/member_pics

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build  # React ビルド

      - name: Rename
        run: mv build/ sort/
        
      - name: Deploy  # S3にデプロイ 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 cp --recursive --region ap-northeast-1 sort s3://italian-red.s3.ap-northeast-1.amazonaws.com/16be-at/
